version: '3'
services:
 # Nginx server configuration   
  web:
    image: nginx:stable-alpine
    container_name: nginx
    depends_on:
      - mysql
      - php
    links:
      - docker-mysql
      - php
    volumes:
      - ./webcontent:/var/www/html
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8080:80"
 # Php-fpm configuration
  php:
    image: php:fpm-alpine3.15
    volumes:
      - ./webcontent:/var/www/html
      - ./php:/usr/local/etc/php/php.ini
 # Mysql configuration
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
        - MYSQL_DATABASE=lannion
        - MYSQL_ROOT_PASSWORD=lannion1234
        - MYSQL_USER=lannion
        - MYSQL_PASSWORD=lannion
    ports:
        - "3306:3306"
    volumes:
        - ./dbdata:/var/lib/mysql